// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdZv17bPvY8e6mP-xmxEednricOX389UI',
    appId: '1:820466289615:android:0094626c9c7c837c7aa0ba',
    messagingSenderId: '820466289615',
    projectId: 'we-chat-fe0b9',
    storageBucket: 'we-chat-fe0b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxtRwInjW-vxAD78mBp-MSUAfSNfsBG3E',
    appId: '1:820466289615:ios:5429b9a5d42908607aa0ba',
    messagingSenderId: '820466289615',
    projectId: 'we-chat-fe0b9',
    storageBucket: 'we-chat-fe0b9.appspot.com',
    androidClientId: '820466289615-s4845at9ee9dn6tn3r3rvseht7phsa5f.apps.googleusercontent.com',
    iosClientId: '820466289615-0phrebjqccrkvk46khnbl7b26ebvmq55.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChatapp',
  );
}
